// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRfjvbLrr7PcNsko2u1AE5bFAq1nrmix4',
    appId: '1:492189475216:web:ec991f60b2b8404f8f9315',
    messagingSenderId: '492189475216',
    projectId: 'drivers-app-e043b',
    authDomain: 'drivers-app-e043b.firebaseapp.com',
    storageBucket: 'drivers-app-e043b.firebasestorage.app',
    measurementId: 'G-WTSYXXQQ4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXzrLvf_RUwNzdm7JlouUKfIfapuNOh04',
    appId: '1:492189475216:android:413325d263975ba88f9315',
    messagingSenderId: '492189475216',
    projectId: 'drivers-app-e043b',
    storageBucket: 'drivers-app-e043b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5cW6iQt6qAEh_wa4vqGWnZro5TTQdUs',
    appId: '1:492189475216:ios:ec29e7be682ee7a28f9315',
    messagingSenderId: '492189475216',
    projectId: 'drivers-app-e043b',
    storageBucket: 'drivers-app-e043b.firebasestorage.app',
    iosBundleId: 'com.example.carApp',
  );
}
